=== CDEApp/CDE/lib/alphafs-111992/Releases/1.0/AlphaFS.UnitTest/PathTestData.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="PathTestData">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Row">
          <xs:complexType>
            <xs:all>
              <xs:element name="Input" type="xs:string" maxOccurs="1" minOccurs="1" />
              <xs:element name="Root" type="xs:string" maxOccurs="1" minOccurs="1" />
              <xs:element name="DirectoryName" type="xs:string" maxOccurs="1" minOccurs="1"/>
              <xs:element name="DirectoryNameWithoutRoot" type="xs:string" maxOccurs="1" minOccurs="1"/>
              <xs:element name="FileName" type="xs:string" maxOccurs="1" minOccurs="1"/>
              <xs:element name="FileNameWithoutExtension" type="xs:string" />
              <xs:element name="Extension" type="xs:string" maxOccurs="1" minOccurs="1"/>
              <xs:element name="FullPath" type="xs:string" maxOccurs="1" minOccurs="1"/>
              <xs:element name="LongFullPath" type="xs:string" maxOccurs="1" minOccurs="1"/>
              <xs:element name="HasFileName" type="xs:boolean" maxOccurs="1" minOccurs="1"/>
              <xs:element name="HasExtension" type="xs:boolean" maxOccurs="1" minOccurs="1"/>
              <xs:element name="IsRooted" type="xs:boolean" maxOccurs="1" minOccurs="1"/>
              <xs:element name="Parent" type="xs:string" maxOccurs="1" minOccurs="1"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== CDEApp/CDE/lib/alphafs-111992/Releases/1.5/AlphaFS.UnitTest/PathTestData.xml
<?xml version="1.0" encoding="utf-8"?>
<PathTestData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PathTestData.xsd">
  <Row>
    <Input>.zip</Input>
    <Root></Root>
    <DirectoryName></DirectoryName>
    <DirectoryNameWithoutRoot></DirectoryNameWithoutRoot>
    <FileName>.zip</FileName>
    <FileNameWithoutExtension></FileNameWithoutExtension>
    <Extension>.zip</Extension>
    <FullPath>C:\.zip</FullPath>
    <LongFullPath>\\?\C:\.zip</LongFullPath>
    <HasExtension>true</HasExtension>
    <HasFileName>true</HasFileName>
    <IsRooted>false</IsRooted>
    <Parent></Parent>
  </Row>
  <Row>
    <Input>C:\Test\File\Foo.txt</Input>
    <Root>C:\</Root>
    <DirectoryName>C:\Test\File</DirectoryName>
    <DirectoryNameWithoutRoot>Test\File</DirectoryNameWithoutRoot>
    <FileName>Foo.txt</FileName>
    <FileNameWithoutExtension>Foo</FileNameWithoutExtension>
    <Extension>.txt</Extension>
    <FullPath>C:\Test\File\Foo.txt</FullPath>
    <LongFullPath>\\?\C:\Test\File\Foo.txt</LongFullPath>
    <HasExtension>true</HasExtension>
    <HasFileName>true</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>C:\Test\File</Parent>
  </Row>
  <Row>
    <Input>C:\</Input>
    <Root>C:\</Root>
    <DirectoryName>C:\</DirectoryName>
    <DirectoryNameWithoutRoot/>
    <FileName/>
    <FileNameWithoutExtension/>
    <Extension/>
    <FullPath>C:\</FullPath>
    <LongFullPath>\\?\C:\</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>false</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>C:\</Parent>
  </Row>
  <Row>
    <Input>\\Server\Share\File.txt</Input>
    <Root>\\Server\Share\</Root>
    <DirectoryName>\\Server\Share\</DirectoryName>
    <DirectoryNameWithoutRoot/>
    <FileName>File.txt</FileName>
    <FileNameWithoutExtension>File</FileNameWithoutExtension>
    <Extension>.txt</Extension>
    <FullPath>\\Server\Share\File.txt</FullPath>
    <LongFullPath>\\?\UNC\Server\Share\File.txt</LongFullPath>
    <HasExtension>true</HasExtension>
    <HasFileName>true</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>\\Server\Share\</Parent>
  </Row>
  <Row>
    <Input>\\?\UNC\Server\Share Name\File Name 1.txt</Input>
    <Root>\\?\UNC\Server\Share Name\</Root>
    <DirectoryName>\\?\UNC\Server\Share Name\</DirectoryName>
    <DirectoryNameWithoutRoot/>
    <FileName>File Name 1.txt</FileName>
    <FileNameWithoutExtension>File Name 1</FileNameWithoutExtension>
    <Extension>.txt</Extension>
    <FullPath>\\?\UNC\Server\Share Name\File Name 1.txt</FullPath>
    <LongFullPath>\\?\UNC\Server\Share Name\File Name 1.txt</LongFullPath>
    <HasExtension>true</HasExtension>
    <HasFileName>true</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>\\?\UNC\Server\Share Name\</Parent>
  </Row>
  <Row>
    <Input>\\Server\Share</Input>
    <Root>\\Server\Share\</Root>
    <DirectoryName>\\Server\Share\</DirectoryName>
    <DirectoryNameWithoutRoot/>
    <FileName/>
    <FileNameWithoutExtension/>
    <Extension/>
    <FullPath>\\Server\Share\</FullPath>
    <LongFullPath>\\?\UNC\Server\Share\</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>false</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>\\Server\Share\</Parent>
  </Row>
  <Row>
    <Input>\\?\C:\Directory\</Input>
    <Root>\\?\C:\</Root>
    <DirectoryName>\\?\C:\Directory</DirectoryName>
    <DirectoryNameWithoutRoot>Directory</DirectoryNameWithoutRoot>
    <FileName/>
    <FileNameWithoutExtension/>
    <Extension/>
    <FullPath>\\?\C:\Directory\</FullPath>
    <LongFullPath>\\?\C:\Directory\</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>false</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>\\?\C:\</Parent>
  </Row>
  <Row>
    <Input>\</Input>
    <Root>\</Root>
    <DirectoryName>\</DirectoryName>
    <DirectoryNameWithoutRoot/>
    <FileName/>
    <FileNameWithoutExtension/>
    <Extension/>
    <FullPath>C:\</FullPath>
    <LongFullPath>\\?\C:\</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>false</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>\</Parent>
  </Row>
  <Row>
    <Input>\Test\File</Input>
    <Root>\</Root>
    <DirectoryName>\Test</DirectoryName>
    <DirectoryNameWithoutRoot>Test</DirectoryNameWithoutRoot>
    <FileName>File</FileName>
    <FileNameWithoutExtension>File</FileNameWithoutExtension>
    <Extension/>
    <FullPath>C:\Test\File</FullPath>
    <LongFullPath>\\?\C:\Test\File</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>true</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>\Test</Parent>
  </Row>
  <Row>
    <Input>\\?\globalroot\device\harddisk0\partition1\</Input>
    <Root>\\?\GLOBALROOT\</Root>
    <DirectoryName>\\?\GLOBALROOT\device\harddisk0\partition1</DirectoryName>
    <DirectoryNameWithoutRoot>device\harddisk0\partition1</DirectoryNameWithoutRoot>
    <FileName/>
    <FileNameWithoutExtension/>
    <Extension/>
    <FullPath>\\?\GLOBALROOT\device\harddisk0\partition1\</FullPath>
    <LongFullPath>\\?\GLOBALROOT\device\harddisk0\partition1\</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>false</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>\\?\GLOBALROOT\device\harddisk0</Parent>
  </Row>
  <Row>
    <Input>\\?\Volume{12345678-aac3-31de-3321-3124565341ed}\Program Files\notepad.exe</Input>
    <Root>\\?\Volume{12345678-aac3-31de-3321-3124565341ed}\</Root>
    <DirectoryName>\\?\Volume{12345678-aac3-31de-3321-3124565341ed}\Program Files</DirectoryName>
    <DirectoryNameWithoutRoot>Program Files</DirectoryNameWithoutRoot>
    <FileName>notepad.exe</FileName>
    <FileNameWithoutExtension>notepad</FileNameWithoutExtension>
    <Extension>.exe</Extension>
    <FullPath>\\?\Volume{12345678-aac3-31de-3321-3124565341ed}\Program Files\notepad.exe</FullPath>
    <LongFullPath>\\?\Volume{12345678-aac3-31de-3321-3124565341ed}\Program Files\notepad.exe</LongFullPath>
  <HasExtension>true</HasExtension><HasFileName>true</HasFileName><IsRooted>true</IsRooted><Parent>\\?\Volume{12345678-aac3-31de-3321-3124565341ed}\Program Files</Parent></Row>
  <Row>
    <Input>Program Files\Microsoft Office</Input>
    <Root/>
    <DirectoryName>Program Files</DirectoryName>
    <DirectoryNameWithoutRoot>Program Files</DirectoryNameWithoutRoot>
    <FileName>Microsoft Office</FileName>
    <FileNameWithoutExtension>Microsoft Office</FileNameWithoutExtension>
    <Extension/>
    <FullPath>C:\Program Files\Microsoft Office</FullPath>
    <LongFullPath>\\?\C:\Program Files\Microsoft Office</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>true</HasFileName>
    <IsRooted>false</IsRooted>
    <Parent>Program Files</Parent>
  </Row>
  <Row>
    <Input>C</Input>
    <Root/>
    <DirectoryName/>
    <DirectoryNameWithoutRoot/>
    <FileName>C</FileName>
    <FileNameWithoutExtension>C</FileNameWithoutExtension>
    <Extension/>
    <FullPath>C:\C</FullPath>
    <LongFullPath>\\?\C:\C</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>true</HasFileName>
    <IsRooted>false</IsRooted>
    <Parent></Parent>
  </Row>
  <Row>
    <Input>C:</Input>
    <Root>C:</Root>
    <DirectoryName/>
    <DirectoryNameWithoutRoot/>
    <FileName/>
    <FileNameWithoutExtension/>
    <Extension/>
    <FullPath>C:</FullPath>
    <LongFullPath>\\?\C:</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>false</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>C:</Parent>
  </Row>
  <Row>
    <Input>C:\</Input>
    <Root>C:\</Root>
    <DirectoryName>C:\</DirectoryName>
    <DirectoryNameWithoutRoot/>
    <FileName/>
    <FileNameWithoutExtension/>
    <Extension/>
    <FullPath>C:\</FullPath>
    <LongFullPath>\\?\C:\</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>false</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>C:\</Parent>
  </Row>
  <Row>
    <Input>C:\a</Input>
    <Root>C:\</Root>
    <DirectoryName>C:\</DirectoryName>
    <DirectoryNameWithoutRoot/>
    <FileName>a</FileName>
    <FileNameWithoutExtension>a</FileNameWithoutExtension>
    <Extension/>
    <FullPath>C:\a</FullPath>
    <LongFullPath>\\?\C:\a</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>true</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>C:\</Parent>
  </Row>
  <Row>
    <Input>C:\a\</Input>
    <Root>C:\</Root>
    <DirectoryName>C:\a</DirectoryName>
    <DirectoryNameWithoutRoot>a</DirectoryNameWithoutRoot>
    <FileName/>
    <FileNameWithoutExtension/>
    <Extension/>
    <FullPath>C:\a\</FullPath>
    <LongFullPath>\\?\C:\a\</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>false</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>C:\</Parent>
  </Row>
  <Row>
    <Input>C:\a\b</Input>
    <Root>C:\</Root>
    <DirectoryName>C:\a</DirectoryName>
    <DirectoryNameWithoutRoot>a</DirectoryNameWithoutRoot>
    <FileName>b</FileName>
    <FileNameWithoutExtension>b</FileNameWithoutExtension>
    <Extension/>
    <FullPath>C:\a\b</FullPath>
    <LongFullPath>\\?\C:\a\b</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>true</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>C:\a</Parent>
  </Row>
  <Row>
    <Input>C:\a\b\</Input>
    <Root>C:\</Root>
    <DirectoryName>C:\a\b</DirectoryName>
    <DirectoryNameWithoutRoot>a\b</DirectoryNameWithoutRoot>
    <FileName/>
    <FileNameWithoutExtension/>
    <Extension/>
    <FullPath>C:\a\b\</FullPath>
    <LongFullPath>\\?\C:\a\b\</LongFullPath>
    <HasExtension>false</HasExtension>
    <HasFileName>false</HasFileName>
    <IsRooted>true</IsRooted>
    <Parent>C:\a</Parent>
